version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brainop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - brain_op_network

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - brain_op_network

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - brain_op_network
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/brainop?schema=public

volumes:
  postgres_data:

networks:
  brain_op_network:
    driver: bridge
